version: 2.1

executors:
  java-executor:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

commands:
  gradle-dependencies:
    steps:
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle.kts" }}
            - v1-dependencies-
      - run: ./gradlew dependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle.kts" }}

jobs:
  test:
    executor: java-executor
    steps:
      - checkout
      - gradle-dependencies
      - run: ./gradlew qualityCheck

  deploy:
    executor: java-executor
    steps:
      - checkout
      - gradle-dependencies
      - run: ./gradlew build
      - run:
          name: Push new docker image
          command: ./gradlew jib

workflows:
  version: 2.1
  testAndDeploy:
    jobs:
      - test
      - deploy:
          filters:
            branches:
              only: master
